/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GateRouteImport } from './routes/gate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrgRouteImport } from './routes/org'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GateRoute = GateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRoute
  '/reserve': typeof ReserveRoute
  '/tickets': typeof TicketsRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRoute
  '/reserve': typeof ReserveRoute
  '/tickets': typeof TicketsRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/events': typeof EventsRoute
  '/gate': typeof GateRoute
  '/login': typeof LoginRoute
  '/org': typeof OrgRoute
  '/reserve': typeof ReserveRoute
  '/tickets': typeof TicketsRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/events'
    | '/gate'
    | '/login'
    | '/org'
    | '/reserve'
    | '/tickets'
    | '/share/$shareToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/checkout'
    | '/events'
    | '/gate'
    | '/login'
    | '/org'
    | '/reserve'
    | '/tickets'
    | '/share/$shareToken'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/events'
    | '/gate'
    | '/login'
    | '/org'
    | '/reserve'
    | '/tickets'
    | '/share/$shareToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CheckoutRoute: typeof CheckoutRoute
  EventsRoute: typeof EventsRoute
  GateRoute: typeof GateRoute
  LoginRoute: typeof LoginRoute
  OrgRoute: typeof OrgRoute
  ReserveRoute: typeof ReserveRoute
  TicketsRoute: typeof TicketsRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate': {
      id: '/gate'
      path: '/gate'
      fullPath: '/gate'
      preLoaderRoute: typeof GateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CheckoutRoute: CheckoutRoute,
  EventsRoute: EventsRoute,
  GateRoute: GateRoute,
  LoginRoute: LoginRoute,
  OrgRoute: OrgRoute,
  ReserveRoute: ReserveRoute,
  TicketsRoute: TicketsRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
